# Generated by Django 4.2.9 on 2024-01-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_stanowisko_alter_person_shirt_size_osoba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoba',
            old_name='nzwisko',
            new_name='nazwisko',
        ),
    ]
