# Generated by Django 4.2.9 on 2024-01-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_nzwisko_osoba_nazwisko'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
